# Generated by Django 4.0.6 on 2022-08-02 16:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menus',
            field=models.ManyToManyField(through='service.RestaurantMenu', to='service.menu'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Rate cant be less then 0'), django.core.validators.MaxValueValidator(5, 'Rate cant be more then 5')]),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantmenu',
            unique_together={('restaurant', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('restaurant_menu', 'user')},
        ),
    ]
